global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.39:8002']
        labels:
          application: 'Account Service Application'
  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.39:8001' ]
        labels:
          application: 'Order Service Application'
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.39:8889' ]
        labels:
          application: 'Api Gateway Service Application'
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.39:8761' ]
        labels:
          application: 'service Registry Application'